"""
Django settings for heimdall project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
# """
import ldap
from django_auth_ldap.config import LDAPSearch, LDAPSearchUnion, GroupOfNamesType
from pathlib import Path
from os.path import join, dirname
import os
from dotenv import load_dotenv

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '¿QUE BUSCAS POR AQUÍ?'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "phonenumber_field",
    'crispy_bootstrap4',
    'crispy_forms',
    'heimdallapp.apps.HeimdallappConfig',
    'Dashboard.apps.DashboardConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heimdall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'heimdall.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "OPTIONS": {
            "read_default_file": "/etc/mysql/my.cnf",
        },
    }
}

# Password validation
#
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'heimdallapp.Trabajador'
# Static files (CSS, JavaScript, Images)'
# https://docs.djangoproject.com/en/5.0/howto/static-files/

import os
#STATICFILES_DIRS = [os.path.join(BASE_DIR, "src/static")]
STATIC_URL = 'static/'
STATIC_ROOT = 'src/static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = 'src/media/'

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")

BASE_CORREOS_TEMPLATE = os.path.join(BASE_DIR, "heimdallapp/correos/")

AUTHENTICATION_BACKENDS = [
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_LDAP_SERVER_URI = os.environ.get("AUTH_LDAP_SERVER_URI")
AUTH_LDAP_BIND_DN = os.environ.get("AUTH_LDAP_BIND_DN")
AUTH_LDAP_BIND_PASSWORD = os.environ.get("AUTH_LDAP_BIND_PASSWORD")
AUTH_LDAP_USER_SEARCH = LDAPSearchUnion(
    LDAPSearch("ou=Solteck,dc=dmheim,dc=dendorgames,dc=es", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
    LDAPSearch("ou=CoreRift,dc=dmheim,dc=dendorgames,dc=es", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
    LDAPSearch("ou=Emeralsolutions,dc=dmheim,dc=dendorgames,dc=es", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
    LDAPSearch("ou=CyberWave,dc=dmheim,dc=dendorgames,dc=es", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"))

AUTH_LDAP_USER_ATTR_MAP = {
    "email": "mail",
    "first_name": "givenName",
    "last_name": "sn",
    "telefono": "telephoneNumber"
}

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    "dc=dmheim,dc=dendorgames,dc=es", ldap.SCOPE_SUBTREE, "(objectClass=group)"
)
AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        "es_tecnico": ["cn=Tecnico,dc=dmheim,dc=dendorgames,dc=es",
                        "cn=DjangoAdministrador,dc=dmheim,dc=dendorgames,dc=es"],
        "es_administrador": "cn=DjangoAdministrador,dc=dmheim,dc=dendorgames,dc=es",
        "is_staff": "cn=SuperAdministrador,dc=dmheim,dc=dendorgames,dc=es",
        "is_superuser": "cn=SuperAdministrador,dc=dmheim,dc=dendorgames,dc=es",

}

AUTH_LDAP_CACHE_GROUPS = False
AUTH_LDAP_CACHE_USERS = False
AUTH_LDAP_CACHE_TIMEOUT = 0
AUTH_LDAP_ALWAYS_UPDATE_USER = True

