# Generated by Django 5.0.6 on 2024-06-17 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heimdallapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 19, 52, 54, 14567)),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_operacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 19, 52, 54, 13935)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 19, 52, 54, 13104)),
        ),
    ]
